#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
"""Generate the Python user_app that NPUSim ``record`` launches for one case.

The wrapper reuses TTK's own ``RTSInterface`` / ``OnlineRtsProfiling`` (pure
Python + ctypes) so the simulation executes the exact same kernel-launch code
path as a real device. Per enabled kernel mode it:
  * loads the pickled ``RTSProfilingParam``
  * runs ``OnlineRtsProfiling(device, param).do()``
  * writes ``output_<i>.bin`` and ``result.json`` into the mode directory

It always exits via ``os._exit(0)`` to bypass ``atexit`` cleanup: camodel
teardown can SIGSEGV the whole process after the program finishes, so record's
exit code is meaningless for TTK — the parent decides from ``result.json``.
"""
import stat
from pathlib import Path

KERNEL_WRAPPER_SCRIPT = r'''#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# Generated by ttk simulator backend. Do not edit.
import json
import os
import pickle
import sys
import traceback
from pathlib import Path

RESULT_FILE = "result.json"


def _write_result(mdir, ok, **fields):
    payload = dict(fields)
    payload["ok"] = ok
    (Path(mdir) / RESULT_FILE).write_text(json.dumps(payload), encoding="utf-8")


def _run_mode(dev, param, mdir):
    from ttk.core_modules.npu.op.rts_sequence import OnlineRtsProfiling
    res = OnlineRtsProfiling(dev, param).do()
    outputs = []
    for idx, ob in enumerate(res.output_bytes or ()):
        if isinstance(ob, str):
            _write_result(mdir, False, error=ob, cycle=str(res.cycle), oob=str(res.oob))
            return False
        outputs.append(bytes(ob) if ob is not None else b"")
        (Path(mdir) / ("output_%d.bin" % idx)).write_bytes(outputs[-1])
    _write_result(mdir, True, cycle=str(res.cycle), oob=str(res.oob))
    return True


def main():
    if len(sys.argv) < 2:
        print("usage: wrapper.py <case_dir>", flush=True)
        os._exit(2)
    case_dir = Path(sys.argv[1])
    try:
        with (case_dir / "switches.pkl").open("rb") as f:
            sw = pickle.load(f)
        from ttk.utilities import set_global_storage
        set_global_storage(sw)
        from ttk.core_modules.runtime.rts_interface import RTSInterface
        # skip_teardown: camodel rtCtxDestroy/rtDeviceReset can busy-spin forever
        # on some cases; the wrapper os._exit(0)s anyway (process exit reclaims
        # camodel resources), so teardown calls are skipped entirely.
        dev = RTSInterface(camodel=True, short_soc_version=sw.short_soc_version,
                           skip_teardown=True)
        ok_all = True
        for mode in ("dyn", "cst", "bin"):
            mdir = case_dir / mode
            if not mdir.is_dir():
                continue
            with (mdir / "param.pkl").open("rb") as f:
                param = pickle.load(f)
            dev.set_device(0)
            try:
                ok = _run_mode(dev, param, mdir)
                ok_all = ok_all and ok
            except Exception as exc:
                ok_all = False
                _write_result(mdir, False, error="%s: %s" % (type(exc).__name__, exc))
        (case_dir / "final_result.json").write_text(
            json.dumps({"ok": ok_all}), encoding="utf-8")
    except Exception:
        (case_dir / "wrapper_error.json").write_text(traceback.format_exc(), encoding="utf-8")
    finally:
        # Bypass atexit/camodel teardown that may SIGSEGV the process.
        os._exit(0)


if __name__ == "__main__":
    main()
'''


ACLNN_WRAPPER_SCRIPT = r'''#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# Generated by ttk simulator backend. Do not edit.
import json
import os
import pickle
import sys
import traceback
from pathlib import Path


def main():
    if len(sys.argv) < 2:
        print("usage: aclnn_wrapper.py <case_dir>", flush=True)
        os._exit(2)
    case_dir = Path(sys.argv[1])
    try:
        with (case_dir / "switches.pkl").open("rb") as f:
            sw = pickle.load(f)
        from ttk.utilities import set_global_storage
        set_global_storage(sw)
        with (case_dir / "context.pkl").open("rb") as f:
            context = pickle.load(f)
        from ttk.core_modules.aclnn import AclInterface
        from ttk.core_modules.npu.op_api.profiling import AclOpExecutor

        # skip_teardown: same camodel teardown busy-spin guard as the kernel wrapper.
        dev = AclInterface(sw.short_soc_version, sw.mode.is_model(), skip_teardown=True)
        dev.set_device(0)
        res = AclOpExecutor(context, dev).do()
        payload = {
            "ok": bool(res.success),
            "api_prof": str(res.api_prof),
            "op_prof": str(res.op_prof),
            "oob": str(res.oob),
            # Optional[str]: json.dumps maps None -> null (str(None) would emit
            # the literal string "None" and be indistinguishable from a real value).
            "deterministic_status": res.deterministic_status,
        }
        if res.success:
            for idx, ob in enumerate(res.output_bytes or ()):
                (case_dir / ("output_%d.bin" % idx)).write_bytes(
                    bytes(ob) if ob is not None else b"")
            with (case_dir / "output_view_shapes.pkl").open("wb") as f:
                pickle.dump(list(res.output_view_shapes or ()), f)
        else:
            payload["error"] = str(res.api_prof)
        (case_dir / "final_result.json").write_text(json.dumps(payload), encoding="utf-8")
    except Exception:
        (case_dir / "wrapper_error.json").write_text(traceback.format_exc(), encoding="utf-8")
    finally:
        # Bypass atexit/camodel teardown that may SIGSEGV the process.
        os._exit(0)


if __name__ == "__main__":
    main()
'''


def write_kernel_wrapper(sw, case_path: Path) -> Path:
    """Write the kernel wrapper .py and make it executable."""
    wrappers_dir = Path(sw.sim_output_dir) / "wrappers"
    wrappers_dir.mkdir(parents=True, exist_ok=True)
    wrapper = wrappers_dir / ("%s_kernel.py" % case_path.name)
    wrapper.write_text(KERNEL_WRAPPER_SCRIPT, encoding="utf-8")
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IEXEC)
    return wrapper


def write_aclnn_wrapper(sw, case_path: Path) -> Path:
    """Write the aclnn wrapper .py and make it executable."""
    wrappers_dir = Path(sw.sim_output_dir) / "wrappers"
    wrappers_dir.mkdir(parents=True, exist_ok=True)
    wrapper = wrappers_dir / ("%s_aclnn.py" % case_path.name)
    wrapper.write_text(ACLNN_WRAPPER_SCRIPT, encoding="utf-8")
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IEXEC)
    return wrapper
